name: Build Xemu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        ARCH: [aarch64]
      fail-fast: false
    steps:
      - name: Build Xemu
        run: |
          # Clone your fork
          git clone --depth 1 https://github.com/Yew12347/termux-packages.git termux-packages
          cd termux-packages

          # Pin the Docker builder image to the Jan 2025 version
          export TERMUX_BUILDER_IMAGE_NAME="ghcr.io/termux/package-builder@sha256:bfbb757453916d3764cbc2201cb8339bcf688d9f1ddfdef276654761e39eb0d5"

          # Build xemu for the selected ARCH
          ./scripts/run-docker.sh ./build-package.sh -f -I -a "${{ matrix.ARCH }}" xemu

          # Move the built .deb out
          mv output/*.deb ../xemu.deb

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: "xemu.deb"
           asset_name: "xemu-${{ matrix.ARCH }}.deb"
           tag: "xemu"
           release_name: "Xemu Original Xbox emulator for Termux"
           overwrite: true
