name: Build bxmu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        ARCH: [aarch64]
      fail-fast: false
    steps:
      - name: clone
        run: |
          wget https://github.com/Yew12347/termux-xemu-req-libs/releases/download/idontknowbro/termux-packages-master.zip
          unzip termux-packages-master.zip
      - name: build
        run: |
          # Build the package inside the Docker container
          cd termux-packages-master
          ./scripts/run-docker.sh ./build-package.sh -f -I -a "${{ matrix.ARCH }}" xemu
          
          mv output/*.deb ../xemu.deb

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: "xemu.deb"
           asset_name: "xemu-${{ matrix.ARCH }}.deb"
           tag: "xemu"
           release_name: "Xemu Original Xbox emulator for Termux"
           overwrite: true
