name: Build Xemuothers
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        ARCH: [aarch64]
      fail-fast: false
    steps:
      - name: Build Xemu
        run: |
          # Download Android NDK
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d $HOME/android
          export NDK=$HOME/android/android-ndk-r25c
          echo "NDK is set to $NDK"
          
          git clone --depth 1 https://github.com/George-Seven/termux-packages
          cd termux-packages
          
          # Run the build inside Docker, passing NDK explicitly
          ./scripts/run-docker.sh -e NDK="$NDK" ./build-package.sh -f -I -a "${{ matrix.ARCH }}" xemu
          
          mv output/*.deb ../xemu.deb

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: "xemu.deb"
           asset_name: "xemu-${{ matrix.ARCH }}.deb"
           tag: "xemu"
           release_name: "Xemu Original Xbox emulator for Termux"
           overwrite: true
